defaultPlacement: beginning
fieldLayouts:
  9d3be8ae-c19c-4b27-afec-3201f012257f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-10T21:10:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 90e3a85e-89e7-4128-b3b6-eea13cf3744f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T21:10:57+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2817d4b1-3f70-458a-81c2-f82491ce138c # Main Color
            handle: null
            includeInCards: false
            instructions: 'Used for icons among other things. '
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5908a1b3-8f83-4255-a64a-0d644ab3f3d9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T21:10:57+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 79574a31-bf11-4c54-a036-bfbb99b93976 # Object Type Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 935e143b-0c8c-4eae-9377-0dbb087fecad
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T21:13:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f46a1722-90eb-4ff8-a5c6-358934674aba # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1be9687e-b827-4719-a79b-bb054e8df3bd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b4e3d229-86d5-46a2-8f4f-40968c505428
        userCondition: null
handle: objectTypes
name: 'Object types'
siteSettings:
  2c2e1c6a-eb4d-44f1-9a43-8d79b326f354: # ES
    hasUrls: true
    template: null
    uriFormat: 'object-types/{slug}'
  547128fa-4529-4483-9968-66425996b69f: # EN
    hasUrls: true
    template: null
    uriFormat: 'object-types/{slug}'
structure:
  maxLevels: null
  uid: 71a7583f-7d34-4156-b561-ddcb41066953
