isPublic: true
name: 'Public Schema'
scope:
  - 'sites.547128fa-4529-4483-9968-66425996b69f:read' # EN
  - 'sites.2c2e1c6a-eb4d-44f1-9a43-8d79b326f354:read' # ES
  - 'sections.ef474ef1-31d2-45c5-8419-cb15202ba296:read' # Guided Experiences Tours
  - 'sections.5d16435b-a18f-4b00-a62e-eb5a38f64561:read' # MPC Data Files
  - 'sections.67672179-938f-44ec-aeea-d4e004a2e66b:read' # Pages
  - 'sections.59e08766-55d3-4cb0-8b02-b406b1ea45d8:read' # Solar system Elements
  - 'nestedentryfields.37d816bc-0a36-4d6d-b947-f1fa804bb53a:read' # Text Body
  - 'nestedentryfields.9f7b6402-ce3b-4a99-9180-c0c6c3915642:read' # flexible
  - 'volumes.e5d596f6-1cc0-4b55-8c33-2a6dae6aa91d:read' # General
  - 'globalsets.8ccd6c1c-8e9b-44e8-93a9-f62589fb4819:read' # Default SEO
  - 'categorygroups.c0bf4db2-5962-4328-abcd-e6a0af1fbfc5:read' # Object types
  - 'categorygroups.fd26bd16-cdc1-44cf-af77-ceb7ecc98e42:read' # Tours
