cardThumbAlignment: end
tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: null
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 0b4b5534-834a-47c5-8d83-6e3028e022a4
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        dateAdded: null
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: 424b7e33-3a03-4de8-b18b-8dda69e45132
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: null
        elementCondition: null
        includeInCards: true
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: 6f6b8af3-4c5d-4935-a63d-2f86b5ed3bb2
        userCondition: null
        warning: null
    name: Content
    uid: e2e58e15-23da-4a6b-aad3-d499aec111f8
    userCondition: null
