color: null
description: null
fieldLayouts:
  84f67ddb-6409-4d18-8544-129795a36da5:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cc9f62fa-64bf-47c2-880b-664f6dcece47
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d31880e6-c769-4211-a62b-edb158f41542
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 8fff3c50-28ba-4af7-8166-e3d82a23ae26 # SEO Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e7e51fd-a1e0-416b-91be-2877ba1bf789
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: acbea415-ee80-409c-90e2-90ac546820a6 # SEO Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7dc9d9cc-a0ad-445d-b9bd-08721e2502e2
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 294114c2-b0a2-4c1e-971b-f6ab75b78e88 # SEO Share Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6bc1433-79b9-45fb-b073-c0fecae2a58c
            userCondition: null
            warning: null
            width: 100
        name: Seo
        uid: b305774e-6257-4f6e-ae4b-14e43bf78412
        userCondition: null
handle: guidedExperiences
hasTitleField: true
icon: null
name: 'Guided Experiences Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
