color: null
description: null
fieldLayouts:
  540efb32-80b5-419f-9af3-ffde8b2e6d57:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-10T21:36:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 09f07a19-e498-4e54-b481-56c87f59a954
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T21:41:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8dcbb92-c170-4e0e-831b-d068fbd2f9b6 # About Image
            handle: logoImage
            includeInCards: false
            instructions: null
            label: 'Logo Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8adfc5d-6153-4474-bf74-0c06d09f76ff
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T21:41:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7970cd65-7a96-418a-8581-d6df4e039e6d # Plain Text
            handle: eyebrowText
            includeInCards: false
            instructions: null
            label: 'Eyeybrow Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4395059c-2dff-4e15-9636-02af10960c87
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T21:41:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7970cd65-7a96-418a-8581-d6df4e039e6d # Plain Text
            handle: headlineText
            includeInCards: false
            instructions: null
            label: Headline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 076cecfc-7fd7-4c3d-baf0-1c1e0de907d2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T21:41:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7970cd65-7a96-418a-8581-d6df4e039e6d # Plain Text
            handle: buttonLabel
            includeInCards: false
            instructions: null
            label: 'Button Label'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b2ccf0a-3c25-49e5-8135-03437e4bcb59
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T21:41:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7970cd65-7a96-418a-8581-d6df4e039e6d # Plain Text
            handle: discoveryLabel
            includeInCards: false
            instructions: null
            label: 'Discovery Label'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 089e4f5a-88e5-40b2-888c-cdb3363344dd
            userCondition: null
            warning: null
            width: 100
        name: Landing
        uid: 6bd66f88-49af-4921-a8f0-a9b03b2613fa
        userCondition: null
handle: landing
hasTitleField: true
icon: null
name: Landing
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
