color: null
description: null
fieldLayouts:
  ec58d409-2cc8-4a47-94f9-774ebe51dc73:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-29T23:57:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a5b6a096-bae8-43a1-8f28-2d6f463f9027
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-29T23:57:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 37b1d17c-d8d5-45f3-9c15-14ef09b62add # Tour Picker
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d68e8d5-fc80-4133-a8b8-13653d4a5862
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-29T23:57:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 96bb1d3d-4098-4112-9dc3-dbffbe908c62 # Tour Preview
            handle: null
            includeInCards: false
            instructions: null
            label: Preview
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f20ffa69-4f6a-4d9d-bb37-4e16c8af24e2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-29T23:57:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4e7f9aec-f2f0-4d0d-bd27-ab2662ab3e08 # Duration
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4a0779b-7825-4c51-813b-4a92aea4ecfa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-29T23:57:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ea7cafd8-b2d5-4ffb-b9fb-9a617eef9dfb # Complexity
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5449cc2-e6db-4c80-bd6a-4bb672a1e40d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-29T23:57:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9f7b6402-ce3b-4a99-9180-c0c6c3915642 # flexible
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94bb81d0-71f2-4e52-b45f-4453423fda85
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-29T23:59:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2c55c489-c226-4b6b-b618-6b8f87b3f700 # Featured Tour
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 737028b4-9c27-4c2a-b8a3-00abfb5deb1a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0d15ded1-467a-4c2f-aae9-01f31af1bfa4
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-29T23:57:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8fff3c50-28ba-4af7-8166-e3d82a23ae26 # SEO Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bb8eb46-4c3e-49c5-af7a-7ea27a770364
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-09-29T23:57:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: acbea415-ee80-409c-90e2-90ac546820a6 # SEO Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9983e6c-ba20-4fda-b7bc-7e6aae09f713
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-09-29T23:57:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 294114c2-b0a2-4c1e-971b-f6ab75b78e88 # SEO Share Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08e10398-5fde-4395-b4e9-79afd8d17473
            userCondition: null
            warning: null
            width: 100
        name: Seo
        uid: 4943d87a-6410-4838-94ae-d9cfe4932c29
        userCondition: null
handle: tour
hasTitleField: true
icon: null
name: Tour
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
