fieldLayouts:
  f9fd1e5a-b2b4-4d31-9663-10318a5c92a8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 96e2805b-5beb-443c-9ae0-8c03438cc369 # Help URL
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed22acda-c4b2-4716-8000-c944c8e4e5c8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: bd7d2ebc-3cf3-4390-b6b5-4e6cc4f1deba # How to use URL
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b90ccedc-b4ec-40e3-9f3a-cc70250274c4
            userCondition: null
            warning: null
            width: 100
        name: URLS
        uid: 3e5e68fe-1700-42cd-b6dc-4c7f59e4a0b1
        userCondition: null
handle: mainMenu
name: 'Main Menu'
sortOrder: 9
