columnSuffix: null
handle: cantoDamAsset
instructions: null
name: 'Canto DAM Asset'
searchable: false
settings:
  errorMessage: 'Component class ''lsst\cantodamassets\fields\CantoDamAsset'' belongs to a disabled plugin (Canto DAM Assets).'
  expectedType: lsst\cantodamassets\fields\CantoDamAsset
  settings:
    __assoc__:
      -
        - cantoAssetPickerType
        - singleImagePicker
translationKeyFormat: null
translationMethod: none
type: craft\fields\MissingField
