defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2f6b435a-5a6c-4f32-b8b5-4aae301d1738
handle: customizeOrbits
maxAuthors: 1
name: 'Customize Orbits'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2c2e1c6a-eb4d-44f1-9a43-8d79b326f354: # ES
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  547128fa-4529-4483-9968-66425996b69f: # EN
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
